### ISSUE TITLE
Question about how to reproducing experiments?

### ISSUE THREAD

**Issue by for-just-we** [sola-st/wasm-binary-security#3]
Hi, author. I'm a green hand on Wasm, and very interested in your findings. Now I try to reproducing your exploit process. But I don't know how to debug wasm modules. Would you mind provide a tutorial on how to use the codes in dir `attack-primitives`, `end-to-end-exploits`.

Thank you very much

**Comment by michaelpradel** [comment]
Thanks for reaching out. I recommend to start by reading our paper (https://www.usenix.org/system/files/sec20-lehmann.pdf) and some of the documentation on WebAssembly. If this leads to more concrete questions, we'll be happy to help.

**Comment by danleh** [comment]
Due to time constraints, I won't be able to give a tutorial. Please refer to our paper for details on how the exploits work, including explanatory figures. For an introduction to WebAssembly, please refer to https://webassembly.org/, the MDN (which has a tutorial at https://developer.mozilla.org/en-US/docs/WebAssembly), or the official W3C specification. For background on runtime exploitation in general, you can read up on buffer overflows, use-after-frees, unlink exploits etc. on Wikipedia or via some search engine. 

If you have a specific question regarding one of our exploits, including a minimal working example and exact description of what you tried, please open a new question.
